services:

    patients-db:
        image: postgres:16
        container_name: patients-db
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-patientsdb}
            POSTGRES_USER: ${POSTGRES_USER:-patient_user}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-patient_pass}
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-patient_user} -d ${POSTGRES_DB:-patientsdb}"]
            interval: 5s
            timeout: 3s
            retries: 10

volumes:
  db_data:
