spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ms-notes

  data:
    mongodb:
      host: localhost
      port: 27017
      username: ${MONGO_INITDB_ROOT_USERNAME:notes_user}
      password: ${MONGO_INITDB_ROOT_PASSWORD:notes_password}
      database: notesdb
      authentication-database: admin

mongock:
  migration-scan-package:
    - com.mr486.msnotes.dbchangelogs

server:
  port: 9002

security:
  app-user:
    username: ${APP_USERNAME:app_user}
    password: ${APP_PASSWORD:app_password}