spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: ms-patients

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB:patientsdb}
    username: ${POSTGRES_USER:patient_user}
    password: ${POSTGRES_PASSWORD:patient_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    change-log: classpath:db/changelog/master.xml

  web:
    resources:
      add-mappings: false

security:
  app-user:
    username: ${APP_USERNAME:app_user}
    password: ${APP_PASSWORD:app_password}

server:
  port: 9001

management:
  endpoints:
    web:
      exposure:
        include: health